"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavigation from "./components/navbar";
import Sidenav from "./components/sidenav";
import Footer from "./components/footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Sales Demo",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const path = usePathname();
  console.log(path);

  return (
    <html lang="en">
      <body className={inter.className}>
        {path !== "/login" && (
          <main>
            <div className="page-wrapper">
              <TopNavigation />
              <div className="page-content-wrapper">
                <Sidenav />
                {children}
              </div>
              <Footer />
            </div>
          </main>
        )}
        {path === "/login" && children}
      </body>
    </html>
  );
}
